### PR TITLE
Fixes syntax error to allow example to run

### PR DESCRIPTION
**Pull request by chuanshi**
Hi! I installed your package from pip, and I found that I needed to change this line to get the example to work.  Is this repository intended to be reflective of the one on pip?  It doesn't seem to be able to find coverage_fix.py.  Thanks!

### CODE REVIEW

**Comment by gusmaogabriels** [comment]
Thanks, Dr. Shi. What version of numpy and scipy are you currently on? That seems like a array-handling issue related to numpy. I have just reinstalled the pypi package via pip and I have had no error pulling up.

**Comment by gusmaogabriels** [comment]
Thanks for the feedback, Dr. Shi.

I have just unninstalled and reinstalled the package via pip and, even
though the code looks the same as the one you cann find in the repository,
I still get the ultimate PSSA-solution.
That seems like more of a numpy version glitch than a problem with the code
itself.
What version of numpy are you using? Currently, I am currently on numpy
1.9.3 and scipy 0.16.0.

By the way, I have not had time yet to find a proper parser to allow CatMap
use the mkin4py linearization under its hood.
Once I am done with some tests I have over these couple of weeks, I should
set some time to look into the CatMap's structure.
Would you have time to converse and exchange thoughts on how it could be
done?

In any case, as a matter of effective matter, I have had an idea regarding
how to use the Hessian info to address the problem topologically. If I
prove I am right, that will definitely detach the IVP from the scope of the
problem.

Should you have any doubts, feel free to reach me anytime.

Best regards,
Gabriel

_--_

_Gabriel S. Gusmão_

gusmaogabriels@gmail.com
» +55 11 99387 3050
   » +1
_951 643 9775_
-  https://www.linkedin.com/in/gusmaogabriels*
  https://github.com/gusmaogabriels
  https://www.researchgate.net/profile/Gabriel_Gusmao

**Comment by gusmaogabriels** [comment]
Dr. Shi,

I have included the changes you have suggested and I have not had any error. 
Therefore, since I do not see any drawbacks, I am merging it.

Thanks again!

**Comment by chuanshi** [comment]
Thanks for the quick response, Gabriel.  I'm actually working on implementing your solver along with a student at SUNCAT as sort of a learning project.  If you're busy with other things, you're free to wait for our implementation.

I can't check the versions I was using to test right this moment, but I remember the bug was caused by `__linalg.qmr` returning two values (the second of which is just an integer for 'did it converge?'), which `__np.array` did not like.  

I'm always open to discuss, but as I'm leaving SUNCAT, soon, it may be more fruitful in the long run to discuss further development of this with the current maintainer of CatMAP at SUNCAT, https://github.com/aayushrs.  I'll point him to this thread, since he's going to be the main one implementing changes to CatMAP in the future.

Best,
Chuan

**Comment by gusmaogabriels** [comment]
That sounds good, Chuan.

I will try to reach Aayush and grab a grasp of the stage of the process he is in and see if I could be of any help. It would indeed be way easier to have someone with in-depth understanding of the catmap's code structure to wrap mkin4py into it.

Best regards,
Gabriel

**Pull request merged**
